version: '3'
services:

  back_flaskk:
    build:
      context: backend
      dockerfile: ../Dockerfile.backend
    container_name: backend-flaskk
    image: flaskpython3.6 #digitalocean.com/flask-python:3.6
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: flaskdb
      MONGODB_USERNAME: Martin
      MONGODB_PASSWORD: Martin
      MONGODB_HOSTNAME: mongodb
    ports:
      - "5000:5000"
    volumes:
      - appdata:/var/www
    depends_on:
      - mongodbb
    networks:
      - frontend
      - backend

  mongodbb:
    image: mongo:4.0.8
    container_name: mongodbb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: your_mongodb_root_password
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - backend




networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
  nginxdata:
    driver: local
  flutterdata:
    driver: local
