ok = "200 OK"
created = "201 CREATED"
no_content = "204 NO CONTENT"

bad_request = "400 BAD REQUEST"
unauthorized = "401 UNAUTHORIZED"
not_found = "404 NOT FOUND"
conflict = "409 CONFLICT"
unsupported_media_type = "415 UNSUPPORTED MEDIA TYPE"
unprocessable_entity = "422 UNPROCESSABLE ENTITY"
